import img1 from "./IMAGENS PROJETO/1.jpg";
import img2 from "./IMAGENS PROJETO/2.webp";
import img3 from "./IMAGENS PROJETO/3.webp";
import img4 from "./IMAGENS PROJETO/4.webp";
import img5 from "./IMAGENS PROJETO/5.jpg";
import img6 from "./IMAGENS PROJETO/6.jpg";
import img7 from "./IMAGENS PROJETO/banner labecomerce.png";
import img8 from "./IMAGENS PROJETO/8.webp";
import img9 from "./IMAGENS PROJETO/9.jpg";
import img10 from "./IMAGENS PROJETO/10.webp";
import img11 from "./IMAGENS PROJETO/11.webp";
import img12 from "./IMAGENS PROJETO/12.webp";

export const ListarProdutos = [
  {
    id: 1,
    image: `${img1}`,
    nomeProduto: `Nike Mario`,
    precoUnitario: 1200,
    categoria: "Deluxe-Edition",
    descricao: "Air Jordan Exclusive Edition Mario",
    desconto: "$ 1.777,00",
    rate: "4,5",
    promocao: true,
  },
  {
    id: 2,
    image: `${img2}`,
    nomeProduto: "Nike Supreme Edition",
    precoUnitario: "$ 200,00",
    categoria: "Premium-Edition",
    descricao: "Nike edição supreme edition 2022",
    desconto: "",
    rate: "4,9",
    promocao: false,
  },
  {
    id: 3,
    image: `${img3}`,
    nomeProduto: "Nike boss Edition for Girls ",
    precoUnitario: "$ 500,00",
    categoria: "Normal Edition",
    descricao: "Edition Girls women",
    desconto: "",
    rate: "4,8",
    promocao: false,
  },
  {
    id: 4,
    image: `${img4}`,
    nomeProduto: "Nike White/Golden lux edition",
    precoUnitario: "$ 400,00",
    categoria: "Summer",
    descricao: "Nike color white golden",
    desconto: "",
    rate: "5,0",
    promocao: false,
  },
  {
    id: 5,
    image: `${img5}`,
    nomeProduto: "Nike Ultra Gear Green",
    precoUnitario: "$ 312,00",
    categoria: "Deluxe-Edition",
    descricao: "Version nike maldives green",
    desconto: "",
    rate: "5,0",
    promocao: false,
  },
  {
    id: 6,
    image: `${img6}`,
    nomeProduto: "Nike Extra edition",
    precoUnitario: "$ 1.199.98",
    categoria: "Deluxe-Edition",
    descricao: "Version exclusive",
    desconto: "2.300,00",
    rate: "4,8",
    promocao: true,
  },
  {
    id: 7,
    image: `${img7}`,
    nomeProduto: "Super Exclusive Edition",
    precoUnitario: "$ 17.562,00",
    categoria: "Deluxe-Edition",
    descricao: "Version exclusive",
    desconto: "$ 24.565",
    rate: "3,5",
    promocao: true,
  },
  {
    id: 8,
    image: `${img8}`,
    nomeProduto: "Premium editon",
    precoUnitario: "$ 27.560,00",
    categoria: "Deluxe-Edition",
    descricao: "Version exclusive",
    desconto: "$ 34.569,00",
    rate: "3,5",
    promocao: true,
  },
  {
    id: 9,
    image: `${img9}`,
    nomeProduto: "Nike Force Premium",
    precoUnitario: "$ 4.563,00",
    categoria: "Deluxe-Edition",
    descricao: "Version exclusive",
    desconto: "",
    rate: "3,5",
    promocao: false,
  },
  {
    id: 10,
    image: `${img10}`,
    nomeProduto: "Nike Deluxe Edition",
    precoUnitario: "$ 4.562,00",
    categoria: "Deluxe-Edition",
    descricao: "Version exclusive",
    desconto: "6.500,00",
    rate: "3,5",
    promocao: true,
  },
  {
    id: 11,
    image: `${img11}`,
    nomeProduto: "Super Exclusive Edition",
    precoUnitario: "$ 4.564,00",
    categoria: "Deluxe-Edition",
    descricao: "Version exclusive",
    desconto: "$ 7.560,00",
    rate: "3,5",
    promocao: true,
  },
  {
    id: 12,
    image: `${img12}`,
    nomeProduto: "Nike Avance Premium Plus",
    precoUnitario: "$ 2.566,00",
    categoria: "Deluxe-Edition",
    descricao: "Version exclusive",
    desconto: "",
    rate: "3,5",
    promocao: false,
  },
];
